### ISSUE TITLE
optional Authentication-Results header (enabled by default)

### ISSUE THREAD

**Issue by jaredj** [smtpd/qpsmtpd#194]
QP [adds auth username and mechanism to the Received: header](https://github.com/smtpd/qpsmtpd/blob/3ef92f214e0b5221af84191c0850218fc80c7bde/lib/Qpsmtpd/SMTP.pm#L852) for authenticated email.

[It is now in an Authentication-Results: header, not in the received header]

This has been [criticized](http://www.nntp.perl.org/group/perl.qpsmtpd/2012/08/msg9956.html) on the mailing list:

>The authentication details, on the other hand, I think should be removed.  
Google will show you [many pairs of (server,auth-username) archived on the 
web](http://www.google.co.uk/search?num=100&q=%22smtp-
auth+username%22+%22mechanism%22) as a result of authenticated emails being sent to mailing lists via qpsmtpd.

>I don't see it as a good idea to give attackers free information about what 
accounts are valid on what servers.  Again, all that a recipient needs to 
know is encapsulated in the "with (E)SMTP(S)A" clause of the header.

Is this a legitimate critique?

**Comment by priyadi** [comment]
No it does not, not in Received header anyway. The $authheader variable is defined, but never make it into Received header. However, the same information can be found in Authentication-Result header added by QP.

I personally need the information. Botnets and trojans frequently spoof information and depending on mail server configuration, it can be very time consuming to find the correct information from log files.

**Comment by msimerson** [comment]
I don't agree with it because:

1. As @priyadi points out, that information was moved to Authentication-Results when I added that header.

2. In the vast majority of mail, the AUTH username is identical to, or a deterministic subset of, the users email address. Generally speaking, nothing is being leaked that wasn't already known. See [RFC 7001](https://tools.ietf.org/html/rfc7001) for more conversation about this.

3. When #2 is not true, having AUTH information in the headers is a helpful aid to answering the "which user account sent this?" question. Especially since QP (nor most recipient validation plugins) does **not** validate the MAIL FROM address. Once I've AUTH'ed as `weak-password@example.com`, relaying for the connection is enabled and the user is freely able to send messages from `target@example.com` as well as `user@target.com` in both the message and envelope fields. Some plugins do tack a couple boards over this open barn door. 

4. Server logs are often ephemeral. After a week or two, they're rotated out and gone from the server. Quite often it takes that long before problems are escalated. Email messages (and their headers) tend to last much longer.

**Comment by jaredj** [comment]
I can dig that.  I just didn't want to merge #193 and forget all about that old debian bug without addressing this additional objection somewhere :)

**Comment by salvis** [comment]
Hmm. The Authentication-Results header is bothering me, too. I'm using auth_imap, and the header exposes `auth=pass (plain) smtp.auth=my_IMAP_user_name;`, which is NOT my usual email address. Actually, my IMAP user name is an email address, but I never use it as such, and I definitely don't want it to become known publicly (and even harvested by bots).

The Authentication-Results header is spilling privileged information that may not be available anywhere else, and having it show up on Google searches is not good. An option to obfuscate or hide it would be very welcome.

**Comment by msimerson** [comment]
I can't imagine many objections to a PR that adds an off switch for that feature. It should remain on by default.

**Comment by msimerson** [comment]
PRs are still welcome, but feature requests aren't. ;-)
